name: 'SSH Push'
description: 'Transfer your folders and execute command with SSH used with NodeJS'
author: 'ErenKrt'
branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  host:
    description: 'IP Address of remote host'
    required: true
  port:
    description: 'Port of SSH Protocol'
    required: false
    default: 22
  username:
    description: 'Username of SSH user'
    required: true
  password:
    description: 'Password of user'
    required: true
  source:
    description: 'Folder/File to be transferred'
    required: true
  destination:
    description: 'Destination of source archive file'
    required: true
  scripts:
    description: 'Execute commands after transfer source file'
    required: false

outputs:
  status:
    description: 'Status'

runs:
  using: 'node18'
  main: 'dist/index.js'