on: [push]

jobs:
  deployment_job:
    runs-on: ubuntu-latest
    name: Deployment Job
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present

    - name: SSH
      uses: ErenKrt/ssh-push@main
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        private_key: ${{ secrets.PRIVATE_KEY }}
        source: "dist/"
        #exclude: |
        #  *.exe
        #scripts: |
        #  cd /home/eren/test && unzip myZipname.zip && rm -r *.zip
        #  cat /home/eren/test/index.js
        #zipname: "myZipname.zip"
        #outdir: "/home/eren/test"

